services:
  redis-service:
    image: "redis:latest"
    ports:
      - "6380:6379"
    networks:
      - ibd-db-net

  ibd-api:
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - redis-service
    networks:
      - ibd-db-net
    env_file: ".env"
    
networks:
  ibd-db-net:
    driver: bridge